export const PROJECTS_CONSTANTS = [
  {
    id: "askbefore.eu",
    i18nKey: "askbeforeEu",
    logo: "/images/projects/askbefore.svg",
    logoWidth: 130,
    logoHeight: 32,
    image: "/images/projects/askbefore.png",
    backgroundColor: "#6152B7",
    technologies: ["NEXT.JS", "PRISMA ORM", "POSTGRESQL"],
    linkHref: "https://askbefore.eu",
    links: [
      { label: "askbefore.eu", href: "https://askbefore.eu" },
      { label: "app.askbefore.eu", href: "https://app.askbefore.eu/" },
    ],
  },
  {
    id: "dessst.ru",
    i18nKey: "dessstRu",
    logo: "/images/projects/dest.svg",
    logoWidth: 107,
    logoHeight: 20,
    image: "/images/projects/dest.png",
    backgroundColor: "#1C7C70",
    technologies: ["Next.js", "Framer Motion", "Styled-Components"],
    linkLabel: "dessst.ru",
    linkHref: "https://web-new.dessst.ru/",
  },
  {
    id: "kazak",
    i18nKey: "kazak",
    logo: "/images/projects/kazak.svg",
    logoWidth: 58,
    logoHeight: 56,
    image: "/images/projects/kazak.png",
    backgroundColor: "#7F0F11",
    technologies: ["NEXT.JS", "ELECTRON.JS", "NODE.JS"],
    linkLabelFromI18n: true,
  },
];

export const COMPACT_PROJECTS_CONSTANTS = [
  {
    id: "kenari",
    i18nKey: "kenari",
    logo: "/images/projects/kenari.svg",
    image: "/images/projects/kenari.png",
    logoWidth: 208,
    logoHeight: 24,
    backgroundColor: "#1C3082",
    technologies: ["HTML/CSS", "JAVASCRIPT"],
    linkLabel: "kenari.ge",
    linkHref: "https://kenari.ge/en",
  },
  {
    id: "maria-portfolio",
    i18nKey: "mariaPortfolio",
    image: "/images/projects/maria.png",
    logo: "/images/projects/maria.svg",
    logoWidth: 20,
    logoHeight: 20,
    backgroundColor: "#2A2A2A",
    technologies: ["NEXT.JS", "FRAMER MOTION"],
    linkLabel: "lubimova.site",
    linkHref: "https://lubimova.site/ru",
  },
];
