export const EXPERIENCE_ENTRIES = [
  {
    id: "distillery",
    iconSrc: "/images/myway/1.svg",
    company: "Distillery",
    stack: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "REST API",
      "Webpack",
      "ESLint",
      "Prettier",
      "pdf-lib",
      "Jest",
      "React Testing Library",
      "Cypress",
      "Storybook",
      "Chart.js",
    ],
  },
  {
    id: "webvalley",
    iconSrc: "/images/myway/2.svg",
    company: "WebValley Studio",
    stack: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Vite",
      "React Router",
      "Styled Components",
      "React Hook Form",
      "Yup",
      "React-i18next",
      "Jest",
      "React Testing Library",
      "Cypress",
      "GitHub",
    ],
  },
  {
    id: "veev",
    iconSrc: "/images/myway/3.svg",
    company: "VEEV Digital",
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Redux Toolkit",
      "styled-components",
      "Framer Motion",
      "Node.js",
      "MongoDB",
      "Electron",
      "React-Virtuoso",
      "React-Zoom-Pan-Pinch",
      "GitLab",
    ],
  },
  {
    id: "askbefore",
    iconSrc: "/images/myway/4.svg",
    company: "AskBefore",
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "React Query",
      "Tailwind CSS",
      "Shadcn/UI",
      "Framer Motion",
      "Prisma ORM",
      "PostgreSQL",
      "Vercel",
      "Google Cloud Storage",
      "Docker",
      "Stripe",
      "Mapbox",
      "Brevo",
      "PostHog",
      "i18n",
      "GitHub",
    ],
  },
];
